Allow multiple response examples to be defined per status code
For example:

  after do |example|
    example.example_group.example_value JSON.parse(response.body, symbolize_names: true) if response
  end

  response 422, 'invalid request' do
    example_context 'name is missing'
      let(:password) { 'secret' }
      run_test!
    end

    example_context 'password is missing' do
      let(:name) { 'bobby' }
      run_test!
    end

    example_context 'bad content type' do
      example_value(
        error: 'bad content type'
      )
    end
  end

Annoyingly you still need a dummy RSpec example to include a static example
value on its own but that's a limitation of RSwag's design.