fix: rubygems-update version for Docker
rubygems-update version grater than 3.5 required ruby version grater than 3.0.0.

```
 > [test-app 3/8] RUN gem update --system:
11.63 ERROR:  Error installing rubygems-update:
11.63   There are no versions of rubygems-update (= 3.5.5) compatible with your Ruby & RubyGems
11.63   rubygems-update requires Ruby version >= 3.0.0. The current ruby version is 2.7.8.225.
11.63 ERROR:  While executing gem ... (NoMethodError)
11.63     undefined method `version' for nil:NilClass
11.65 Updating rubygems-update
```

Fix rubygems-update version for Docker ruby 2.7.